### ISSUE TITLE
bug: Don't override system environment variables

### ISSUE THREAD

**Issue by Benjamin-Dobell** [gobuffalo/envy#44] opened 2022-10-04 12:51 UTC
#### Description

Please don't override the shell/system's environment variables in your `init()` method.

https://github.com/gobuffalo/envy/blob/v1/envy.go#L85

#### Expected Behavior

Ideally don't cause any side effects that affect code outside your modules at all in your `init()`.

https://github.com/gobuffalo/envy/blame/v1/envy.go#L34-L37

However, at a minimum, the environment variables from the shell/system should take precedence unless someone explicitly says otherwise.

### Actual Behavior

In my case, a dependency of a dependency is using `envy`. I was _very_ confused as to what was going on with my environment variables.

Simply including `envy` in a project breaks the ability for any other modules to use dotenv's `Load()` functionality, because `Overload()` has already been called. 

### To Reproduce

1. In any project using envy...
2. Create a `.env` with an environment variable set to one value.
3. Execute the project in a shell that already has the environment variable defined.
4. Note that the value in `.env` overwrote the shell defined environment variable.

**Comment by sio4** [comment] 2022-10-04 13:34
Thanks for reporting the issue.

This (bug-ish) behavior is a known issue of v1 series and will be fixed in v2 soon. (already fixed by #41 but not yet released)

duplicate of #36

**Closed as completed** 2022-10-04 13:37 UTC
Labels: s: duplicate
